// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: ScreenUI

#ifndef _SCREENUI_UI_H
#define _SCREENUI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

///////////////////// SCREENS ////////////////////

#include "ui_Screen1.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_white_writing3_png);    // assets/white writing3.png
LV_IMG_DECLARE(ui_img_warning_unlit_png);    // assets/warning_unlit.png
LV_IMG_DECLARE(ui_img_warning_lit_png);    // assets/warning_lit.png
LV_IMG_DECLARE(ui_img_fullbeam_unlit_png);    // assets/fullbeam_unlit.png
LV_IMG_DECLARE(ui_img_fullbeam_lit_png);    // assets/fullbeam_lit.png
LV_IMG_DECLARE(ui_img_indicator_right_unlit_png);    // assets/indicator_right_unlit.png
LV_IMG_DECLARE(ui_img_indicator_right_partial_png);    // assets/indicator_right_partial.png
LV_IMG_DECLARE(ui_img_indicator_right_partial2_png);    // assets/indicator_right_partial2.png
LV_IMG_DECLARE(ui_img_indicator_right_lit_png);    // assets/indicator_right_lit.png
LV_IMG_DECLARE(ui_img_status_batt_ok_png);    // assets/status_batt_ok.png
LV_IMG_DECLARE(ui_img_status_batt_warn_png);    // assets/status_batt_warn.png
LV_IMG_DECLARE(ui_img_status_temp_ok_png);    // assets/status_temp_ok.png
LV_IMG_DECLARE(ui_img_status_temp_warn_png);    // assets/status_temp_warn.png
LV_IMG_DECLARE(ui_img_status_comms_ok_png);    // assets/status_comms_ok.png
LV_IMG_DECLARE(ui_img_status_comms_warn_png);    // assets/status_comms_warn.png
LV_IMG_DECLARE(ui_img_status_solar_ok_png);    // assets/status_solar_ok.png
LV_IMG_DECLARE(ui_img_status_solar_warn_png);    // assets/status_solar_warn.png
LV_IMG_DECLARE(ui_img_status_ctrl_ok_png);    // assets/status_ctrl_ok.png
LV_IMG_DECLARE(ui_img_status_ctrl_warn_png);    // assets/status_ctrl_warn.png
LV_IMG_DECLARE(ui_img_status_motor_ok_png);    // assets/status_motor_ok.png
LV_IMG_DECLARE(ui_img_status_motor_warn_png);    // assets/status_motor_warn.png

// FONTS
LV_FONT_DECLARE(ui_font_InterMedium18);
LV_FONT_DECLARE(ui_font_InterMedium20);
LV_FONT_DECLARE(ui_font_InterSemiBold22);
LV_FONT_DECLARE(ui_font_RajdhaniBold40);
LV_FONT_DECLARE(ui_font_RajdhaniMedium32);
LV_FONT_DECLARE(ui_font_RajdhaniSemiBold30);
LV_FONT_DECLARE(ui_font_RajdhaniSemiBold96);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
