// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: ScreenUI

#include "ui.h"

void ui_comp_WarningButton_create_hook(lv_obj_t * comp)
{
}
