// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: ScreenUI

#include "ui.h"

lv_obj_t * uic_WarningText;
lv_obj_t * uic_StatMotorWarn;
lv_obj_t * uic_StatMotorOk;
lv_obj_t * uic_StatCtrlWarn;
lv_obj_t * uic_StatCtrlOk;
lv_obj_t * uic_StatSolarWarn;
lv_obj_t * uic_StatCommsWarn;
lv_obj_t * uic_StatCommsOk;
lv_obj_t * uic_StatTempWarn;
lv_obj_t * uic_StatTempOk;
lv_obj_t * uic_StatBattWarn;
lv_obj_t * uic_StatBattOk;
lv_obj_t * uic_FullLitLeftIndicator;
lv_obj_t * uic_SecondPartLitLeftIndicator;
lv_obj_t * uic_FirstPartLitLeftIndicator;
lv_obj_t * uic_UnlitLeftIndicator;
lv_obj_t * uic_FullLitRightIndicator;
lv_obj_t * uic_SecondPartLitRightIndicator;
lv_obj_t * uic_FirstPartLitRightIndicator;
lv_obj_t * uic_UnlitRightIndicator;
lv_obj_t * uic_LitFullBeam;
lv_obj_t * uic_UnlitFullBeam;
lv_obj_t * uic_LitWarningLight;
lv_obj_t * uic_UnlitWarningLight;
lv_obj_t * uic_PWRIN;
lv_obj_t * uic_PWROUT;
lv_obj_t * uic_PowerIn;
lv_obj_t * uic_PowerOut;
lv_obj_t * uic_SteeringAngleLabel;
lv_obj_t * uic_DrivingStateLabel;
lv_obj_t * uic_BattPerc2;
lv_obj_t * uic_BattPercSlider3;
lv_obj_t * uic_BattPerc4;
lv_obj_t * uic_BattPercLabel;
lv_obj_t * uic_BattTempLabel;
lv_obj_t * uic_SEMLogo;
lv_obj_t * uic_SpeedSlider1;
lv_obj_t * uic_Tick21;
lv_obj_t * uic_Tick20;
lv_obj_t * uic_Tick19;
lv_obj_t * uic_Tick18;
lv_obj_t * uic_Tick17;
lv_obj_t * uic_Tick16;
lv_obj_t * uic_Tick15;
lv_obj_t * uic_Tick14;
lv_obj_t * uic_Tick13;
lv_obj_t * uic_Tick12;
lv_obj_t * uic_Speed1;
lv_obj_t * uic_kph1;
lv_obj_t * uic_Tick11;
lv_obj_t * uic_Panel11;
lv_obj_t * uic_Panel10;
lv_obj_t * uic_Speedometer;
lv_obj_t * uic_Screen1;
lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Speedometer = NULL;
lv_obj_t * ui_Panel10 = NULL;
lv_obj_t * ui_Panel11 = NULL;
lv_obj_t * ui_Tick11 = NULL;
lv_obj_t * ui_kph1 = NULL;
lv_obj_t * ui_Speed1 = NULL;
lv_obj_t * ui_Tick12 = NULL;
lv_obj_t * ui_Tick13 = NULL;
lv_obj_t * ui_Tick14 = NULL;
lv_obj_t * ui_Tick15 = NULL;
lv_obj_t * ui_Tick16 = NULL;
lv_obj_t * ui_Tick17 = NULL;
lv_obj_t * ui_Tick18 = NULL;
lv_obj_t * ui_Tick19 = NULL;
lv_obj_t * ui_Tick20 = NULL;
lv_obj_t * ui_Tick21 = NULL;
lv_obj_t * ui_SpeedSlider1 = NULL;
lv_obj_t * ui_SEMLogo = NULL;
lv_obj_t * ui_BattTempLabel = NULL;
lv_obj_t * ui_BattPercLabel = NULL;
lv_obj_t * ui_BattPerc4 = NULL;
lv_obj_t * ui_BattPercSlider3 = NULL;
lv_obj_t * ui_BattPerc2 = NULL;
lv_obj_t * ui_DrivingStateLabel = NULL;
lv_obj_t * ui_SteeringAngleLabel = NULL;
lv_obj_t * ui_PowerOut = NULL;
lv_obj_t * ui_PowerIn = NULL;
lv_obj_t * ui_PWROUT = NULL;
lv_obj_t * ui_PWRIN = NULL;
lv_obj_t * ui_UnlitWarningLight = NULL;
lv_obj_t * ui_LitWarningLight = NULL;
lv_obj_t * ui_UnlitFullBeam = NULL;
lv_obj_t * ui_LitFullBeam = NULL;
lv_obj_t * ui_UnlitRightIndicator = NULL;
lv_obj_t * ui_FirstPartLitRightIndicator = NULL;
lv_obj_t * ui_SecondPartLitRightIndicator = NULL;
lv_obj_t * ui_FullLitRightIndicator = NULL;
lv_obj_t * ui_UnlitLeftIndicator = NULL;
lv_obj_t * ui_FirstPartLitLeftIndicator = NULL;
lv_obj_t * ui_SecondPartLitLeftIndicator = NULL;
lv_obj_t * ui_FullLitLeftIndicator = NULL;
lv_obj_t * ui_StatBattOk = NULL;
lv_obj_t * ui_StatBattWarn = NULL;
lv_obj_t * ui_StatTempOk = NULL;
lv_obj_t * ui_StatTempWarn = NULL;
lv_obj_t * ui_StatCommsOk = NULL;
lv_obj_t * ui_StatCommsWarn = NULL;
lv_obj_t * ui_StatSolarOk = NULL;
lv_obj_t * ui_StatSolarWarn = NULL;
lv_obj_t * ui_StatCtrlOk = NULL;
lv_obj_t * ui_StatCtrlWarn = NULL;
lv_obj_t * ui_StatMotorOk = NULL;
lv_obj_t * ui_StatMotorWarn = NULL;
lv_obj_t * ui_WarningText = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Screen1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Background);
    ui_object_set_themeable_style_property(ui_Screen1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Background);

    ui_Speedometer = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Speedometer, 400);
    lv_obj_set_height(ui_Speedometer, 400);
    lv_obj_set_x(ui_Speedometer, 0);
    lv_obj_set_y(ui_Speedometer, 12);
    lv_obj_set_align(ui_Speedometer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Speedometer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_width(ui_Speedometer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel10 = lv_obj_create(ui_Speedometer);
    lv_obj_set_width(ui_Panel10, 400);
    lv_obj_set_height(ui_Panel10, 400);
    lv_obj_set_align(ui_Panel10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Panel10, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Background);
    ui_object_set_themeable_style_property(ui_Panel10, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Background);
    lv_obj_set_style_border_width(ui_Panel10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel11 = lv_obj_create(ui_Speedometer);
    lv_obj_set_width(ui_Panel11, 376);
    lv_obj_set_height(ui_Panel11, 376);
    lv_obj_set_align(ui_Panel11, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel11, 500, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Panel11, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Background);
    ui_object_set_themeable_style_property(ui_Panel11, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Background);
    lv_obj_set_style_border_color(ui_Panel11, lv_color_hex(0x2D323C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Tick11 = lv_obj_create(ui_Speedometer);
    lv_obj_set_width(ui_Tick11, 4);
    lv_obj_set_height(ui_Tick11, 35);
    lv_obj_set_x(ui_Tick11, -115);
    lv_obj_set_y(ui_Tick11, 121);
    lv_obj_set_align(ui_Tick11, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Tick11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Tick11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Tick11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Tick11, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_TextColour);
    ui_object_set_themeable_style_property(ui_Tick11, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_TextColour);
    lv_obj_set_style_border_width(ui_Tick11, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Tick11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Tick11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Tick11, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Tick11, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_Tick11, 450, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_kph1 = lv_label_create(ui_Speedometer);
    lv_obj_set_width(ui_kph1, LV_SIZE_CONTENT);   /// 10
    lv_obj_set_height(ui_kph1, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_x(ui_kph1, 0);
    lv_obj_set_y(ui_kph1, 35);
    lv_obj_set_align(ui_kph1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_kph1, "kph");
    ui_object_set_themeable_style_property(ui_kph1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_TextColour);
    ui_object_set_themeable_style_property(ui_kph1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_TextColour);
    lv_obj_set_style_text_font(ui_kph1, &ui_font_InterMedium20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_kph1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_kph1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Speed1 = lv_label_create(ui_Speedometer);
    lv_obj_set_width(ui_Speed1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Speed1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Speed1, 0);
    lv_obj_set_y(ui_Speed1, -20);
    lv_obj_set_align(ui_Speed1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Speed1, "0");
    ui_object_set_themeable_style_property(ui_Speed1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_TextColour);
    ui_object_set_themeable_style_property(ui_Speed1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_TextColour);
    lv_obj_set_style_text_font(ui_Speed1, &ui_font_RajdhaniSemiBold96, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Tick12 = lv_obj_create(ui_Speedometer);
    lv_obj_set_width(ui_Tick12, 4);
    lv_obj_set_height(ui_Tick12, 35);
    lv_obj_set_x(ui_Tick12, -148);
    lv_obj_set_y(ui_Tick12, 62);
    lv_obj_set_align(ui_Tick12, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Tick12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Tick12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Tick12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Tick12, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_TextColour);
    ui_object_set_themeable_style_property(ui_Tick12, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_TextColour);
    lv_obj_set_style_border_width(ui_Tick12, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Tick12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Tick12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Tick12, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Tick12, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_Tick12, 650, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Tick13 = lv_obj_create(ui_Speedometer);
    lv_obj_set_width(ui_Tick13, 4);
    lv_obj_set_height(ui_Tick13, 35);
    lv_obj_set_x(ui_Tick13, -152);
    lv_obj_set_y(ui_Tick13, -8);
    lv_obj_set_align(ui_Tick13, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Tick13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Tick13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Tick13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Tick13, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_TextColour);
    ui_object_set_themeable_style_property(ui_Tick13, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_TextColour);
    lv_obj_set_style_border_width(ui_Tick13, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Tick13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Tick13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Tick13, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Tick13, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_Tick13, 970, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Tick14 = lv_obj_create(ui_Speedometer);
    lv_obj_set_width(ui_Tick14, 4);
    lv_obj_set_height(ui_Tick14, 35);
    lv_obj_set_x(ui_Tick14, -127);
    lv_obj_set_y(ui_Tick14, -76);
    lv_obj_set_align(ui_Tick14, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Tick14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Tick14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Tick14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Tick14, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_TextColour);
    ui_object_set_themeable_style_property(ui_Tick14, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_TextColour);
    lv_obj_set_style_border_width(ui_Tick14, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Tick14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Tick14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Tick14, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Tick14, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_Tick14, 1235, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Tick15 = lv_obj_create(ui_Speedometer);
    lv_obj_set_width(ui_Tick15, 4);
    lv_obj_set_height(ui_Tick15, 35);
    lv_obj_set_x(ui_Tick15, -71);
    lv_obj_set_y(ui_Tick15, -121);
    lv_obj_set_align(ui_Tick15, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Tick15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Tick15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Tick15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Tick15, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_TextColour);
    ui_object_set_themeable_style_property(ui_Tick15, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_TextColour);
    lv_obj_set_style_border_width(ui_Tick15, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Tick15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Tick15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Tick15, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Tick15, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_Tick15, 1500, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Tick16 = lv_obj_create(ui_Speedometer);
    lv_obj_set_width(ui_Tick16, 4);
    lv_obj_set_height(ui_Tick16, 35);
    lv_obj_set_x(ui_Tick16, -1);
    lv_obj_set_y(ui_Tick16, -173);
    lv_obj_set_align(ui_Tick16, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Tick16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Tick16, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Tick16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Tick16, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_TextColour);
    ui_object_set_themeable_style_property(ui_Tick16, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_TextColour);
    lv_obj_set_style_border_width(ui_Tick16, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Tick16, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Tick16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Tick16, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Tick16, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_Tick16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Tick17 = lv_obj_create(ui_Speedometer);
    lv_obj_set_width(ui_Tick17, 4);
    lv_obj_set_height(ui_Tick17, 35);
    lv_obj_set_x(ui_Tick17, 83);
    lv_obj_set_y(ui_Tick17, -154);
    lv_obj_set_align(ui_Tick17, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Tick17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Tick17, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Tick17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Tick17, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_TextColour);
    ui_object_set_themeable_style_property(ui_Tick17, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_TextColour);
    lv_obj_set_style_border_width(ui_Tick17, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Tick17, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Tick17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Tick17, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Tick17, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_Tick17, 300, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Tick18 = lv_obj_create(ui_Speedometer);
    lv_obj_set_width(ui_Tick18, 4);
    lv_obj_set_height(ui_Tick18, 35);
    lv_obj_set_x(ui_Tick18, 152);
    lv_obj_set_y(ui_Tick18, -97);
    lv_obj_set_align(ui_Tick18, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Tick18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Tick18, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Tick18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Tick18, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_TextColour);
    ui_object_set_themeable_style_property(ui_Tick18, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_TextColour);
    lv_obj_set_style_border_width(ui_Tick18, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Tick18, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Tick18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Tick18, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Tick18, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_Tick18, 530, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Tick19 = lv_obj_create(ui_Speedometer);
    lv_obj_set_width(ui_Tick19, 4);
    lv_obj_set_height(ui_Tick19, 35);
    lv_obj_set_x(ui_Tick19, 187);
    lv_obj_set_y(ui_Tick19, -14);
    lv_obj_set_align(ui_Tick19, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Tick19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Tick19, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Tick19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Tick19, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_TextColour);
    ui_object_set_themeable_style_property(ui_Tick19, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_TextColour);
    lv_obj_set_style_border_width(ui_Tick19, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Tick19, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Tick19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Tick19, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Tick19, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_Tick19, 800, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Tick20 = lv_obj_create(ui_Speedometer);
    lv_obj_set_width(ui_Tick20, 4);
    lv_obj_set_height(ui_Tick20, 35);
    lv_obj_set_x(ui_Tick20, 182);
    lv_obj_set_y(ui_Tick20, 72);
    lv_obj_set_align(ui_Tick20, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Tick20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Tick20, lv_color_hex(0xC8CCD8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Tick20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Tick20, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_TextColour);
    ui_object_set_themeable_style_property(ui_Tick20, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_TextColour);
    lv_obj_set_style_border_width(ui_Tick20, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Tick20, lv_color_hex(0xC8CCD8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Tick20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Tick20, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Tick20, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_Tick20, 1100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Tick21 = lv_obj_create(ui_Speedometer);
    lv_obj_set_width(ui_Tick21, 4);
    lv_obj_set_height(ui_Tick21, 35);
    lv_obj_set_x(ui_Tick21, 140);
    lv_obj_set_y(ui_Tick21, 147);
    lv_obj_set_align(ui_Tick21, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Tick21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Tick21, lv_color_hex(0xC8CCD8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Tick21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Tick21, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_TextColour);
    ui_object_set_themeable_style_property(ui_Tick21, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_TextColour);
    lv_obj_set_style_border_width(ui_Tick21, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Tick21, lv_color_hex(0xC8CCD8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Tick21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Tick21, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Tick21, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_Tick21, 1300, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpeedSlider1 = lv_arc_create(ui_Speedometer);
    lv_obj_set_width(ui_SpeedSlider1, 400);
    lv_obj_set_height(ui_SpeedSlider1, 400);
    lv_obj_set_align(ui_SpeedSlider1, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_SpeedSlider1, 0);
    lv_obj_set_style_arc_color(ui_SpeedSlider1, lv_color_hex(0x241E4D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_SpeedSlider1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_SpeedSlider1, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_SpeedSlider1, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_shadow_color(ui_SpeedSlider1, lv_color_hex(0x3AA0FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SpeedSlider1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_SpeedSlider1, 14, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_SpeedSlider1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_SpeedSlider1, lv_color_hex(0x3AA0FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_SpeedSlider1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_SpeedSlider1, 15, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_SpeedSlider1, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_blend_mode(ui_SpeedSlider1, LV_BLEND_MODE_NORMAL, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_SpeedSlider1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_SEMLogo = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_SEMLogo, &ui_img_white_writing3_png);
    lv_obj_set_width(ui_SEMLogo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SEMLogo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SEMLogo, -267);
    lv_obj_set_y(ui_SEMLogo, -191);
    lv_obj_set_align(ui_SEMLogo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SEMLogo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SEMLogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BattTempLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_BattTempLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BattTempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BattTempLabel, 300);
    lv_obj_set_y(ui_BattTempLabel, -100);
    lv_obj_set_align(ui_BattTempLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BattTempLabel, "Battery Overheating!");
    lv_obj_set_style_text_color(ui_BattTempLabel, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BattTempLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_BattTempLabel, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_BattTempLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BattPercLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_BattPercLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BattPercLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BattPercLabel, 300);
    lv_obj_set_y(ui_BattPercLabel, 0);
    lv_obj_set_align(ui_BattPercLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BattPercLabel, "Battery Low!");
    lv_obj_set_style_text_color(ui_BattPercLabel, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BattPercLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_BattPercLabel, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_BattPercLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BattPerc4 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_BattPerc4, 300);
    lv_obj_set_height(ui_BattPerc4, 48);
    lv_obj_set_x(ui_BattPerc4, 251);
    lv_obj_set_y(ui_BattPerc4, -200);
    lv_obj_set_align(ui_BattPerc4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BattPerc4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_BattPerc4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Background);
    ui_object_set_themeable_style_property(ui_BattPerc4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Background);
    lv_obj_set_style_border_width(ui_BattPerc4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BattPercSlider3 = lv_slider_create(ui_BattPerc4);
    lv_slider_set_value(ui_BattPercSlider3, 100, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_BattPercSlider3) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_BattPercSlider3, 0,
                                                                                                    LV_ANIM_OFF);
    lv_obj_set_width(ui_BattPercSlider3, 200);
    lv_obj_set_height(ui_BattPercSlider3, 30);
    lv_obj_set_x(ui_BattPercSlider3, 30);
    lv_obj_set_y(ui_BattPercSlider3, 0);
    lv_obj_set_align(ui_BattPercSlider3, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_BattPercSlider3, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BattPercSlider3, lv_color_hex(0x241E4D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BattPercSlider3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_BattPercSlider3, 25, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BattPercSlider3, lv_color_hex(0x19E63C), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BattPercSlider3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BattPercSlider3, lv_color_hex(0x19E63C), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BattPercSlider3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BattPercSlider3, 12, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BattPercSlider3, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_blend_mode(ui_BattPercSlider3, LV_BLEND_MODE_NORMAL, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_BattPercSlider3, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_BattPerc2 = lv_label_create(ui_BattPerc4);
    lv_obj_set_width(ui_BattPerc2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BattPerc2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BattPerc2, -115);
    lv_obj_set_y(ui_BattPerc2, 0);
    lv_obj_set_align(ui_BattPerc2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BattPerc2, "100%");
    ui_object_set_themeable_style_property(ui_BattPerc2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_TextColour);
    ui_object_set_themeable_style_property(ui_BattPerc2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_TextColour);
    lv_obj_set_style_text_font(ui_BattPerc2, &ui_font_RajdhaniSemiBold30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DrivingStateLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_DrivingStateLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DrivingStateLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DrivingStateLabel, -50);
    lv_obj_set_y(ui_DrivingStateLabel, 125);
    lv_obj_set_align(ui_DrivingStateLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DrivingStateLabel, "N");
    lv_obj_set_style_text_color(ui_DrivingStateLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DrivingStateLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DrivingStateLabel, &ui_font_RajdhaniBold40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SteeringAngleLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_SteeringAngleLabel, LV_SIZE_CONTENT);   /// 10
    lv_obj_set_height(ui_SteeringAngleLabel, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_x(ui_SteeringAngleLabel, 50);
    lv_obj_set_y(ui_SteeringAngleLabel, 125);
    lv_obj_set_align(ui_SteeringAngleLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SteeringAngleLabel, "±0°");
    ui_object_set_themeable_style_property(ui_SteeringAngleLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_TextColour);
    ui_object_set_themeable_style_property(ui_SteeringAngleLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_TextColour);
    lv_obj_set_style_text_font(ui_SteeringAngleLabel, &ui_font_RajdhaniMedium32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PowerOut = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_PowerOut, LV_SIZE_CONTENT);   /// 10
    lv_obj_set_height(ui_PowerOut, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_x(ui_PowerOut, 300);
    lv_obj_set_y(ui_PowerOut, 200);
    lv_obj_set_align(ui_PowerOut, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PowerOut, "-0W");
    lv_obj_set_style_text_color(ui_PowerOut, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PowerOut, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PowerOut, &ui_font_RajdhaniBold40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PowerIn = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_PowerIn, LV_SIZE_CONTENT);   /// 10
    lv_obj_set_height(ui_PowerIn, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_x(ui_PowerIn, -300);
    lv_obj_set_y(ui_PowerIn, 200);
    lv_obj_set_align(ui_PowerIn, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PowerIn, "+0W");
    lv_obj_set_style_text_color(ui_PowerIn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PowerIn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PowerIn, &ui_font_RajdhaniBold40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PWROUT = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_PWROUT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PWROUT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PWROUT, 300);
    lv_obj_set_y(ui_PWROUT, 160);
    lv_obj_set_align(ui_PWROUT, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PWROUT, "PWR Out:");
    lv_obj_set_style_text_color(ui_PWROUT, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PWROUT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PWROUT, &ui_font_RajdhaniSemiBold30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PWRIN = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_PWRIN, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PWRIN, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PWRIN, -300);
    lv_obj_set_y(ui_PWRIN, 160);
    lv_obj_set_align(ui_PWRIN, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PWRIN, "PWR In:");
    lv_obj_set_style_text_color(ui_PWRIN, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PWRIN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PWRIN, &ui_font_RajdhaniSemiBold30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UnlitWarningLight = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_UnlitWarningLight, &ui_img_warning_unlit_png);
    lv_obj_set_width(ui_UnlitWarningLight, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_UnlitWarningLight, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_UnlitWarningLight, 30);
    lv_obj_set_y(ui_UnlitWarningLight, -85);
    lv_obj_set_align(ui_UnlitWarningLight, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_UnlitWarningLight, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_UnlitWarningLight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LitWarningLight = lv_img_create(ui_UnlitWarningLight);
    lv_img_set_src(ui_LitWarningLight, &ui_img_warning_lit_png);
    lv_obj_set_width(ui_LitWarningLight, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LitWarningLight, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LitWarningLight, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LitWarningLight, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_LitWarningLight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_blend_mode(ui_LitWarningLight, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_LitWarningLight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UnlitFullBeam = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_UnlitFullBeam, &ui_img_fullbeam_unlit_png);
    lv_obj_set_width(ui_UnlitFullBeam, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_UnlitFullBeam, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_UnlitFullBeam, -30);
    lv_obj_set_y(ui_UnlitFullBeam, -85);
    lv_obj_set_align(ui_UnlitFullBeam, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_UnlitFullBeam, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_UnlitFullBeam, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LitFullBeam = lv_img_create(ui_UnlitFullBeam);
    lv_img_set_src(ui_LitFullBeam, &ui_img_fullbeam_lit_png);
    lv_obj_set_width(ui_LitFullBeam, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LitFullBeam, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LitFullBeam, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LitFullBeam, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_LitFullBeam, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_blend_mode(ui_LitFullBeam, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_LitFullBeam, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UnlitRightIndicator = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_UnlitRightIndicator, &ui_img_indicator_right_unlit_png);
    lv_obj_set_width(ui_UnlitRightIndicator, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_UnlitRightIndicator, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_UnlitRightIndicator, 75);
    lv_obj_set_y(ui_UnlitRightIndicator, -10);
    lv_obj_set_align(ui_UnlitRightIndicator, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_UnlitRightIndicator, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_UnlitRightIndicator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_FirstPartLitRightIndicator = lv_img_create(ui_UnlitRightIndicator);
    lv_img_set_src(ui_FirstPartLitRightIndicator, &ui_img_indicator_right_partial_png);
    lv_obj_set_width(ui_FirstPartLitRightIndicator, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FirstPartLitRightIndicator, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_FirstPartLitRightIndicator, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_FirstPartLitRightIndicator, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_FirstPartLitRightIndicator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_blend_mode(ui_FirstPartLitRightIndicator, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_FirstPartLitRightIndicator, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SecondPartLitRightIndicator = lv_img_create(ui_UnlitRightIndicator);
    lv_img_set_src(ui_SecondPartLitRightIndicator, &ui_img_indicator_right_partial2_png);
    lv_obj_set_width(ui_SecondPartLitRightIndicator, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SecondPartLitRightIndicator, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SecondPartLitRightIndicator, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SecondPartLitRightIndicator, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SecondPartLitRightIndicator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_blend_mode(ui_SecondPartLitRightIndicator, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_SecondPartLitRightIndicator, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FullLitRightIndicator = lv_img_create(ui_UnlitRightIndicator);
    lv_img_set_src(ui_FullLitRightIndicator, &ui_img_indicator_right_lit_png);
    lv_obj_set_width(ui_FullLitRightIndicator, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FullLitRightIndicator, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_FullLitRightIndicator, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_FullLitRightIndicator, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_FullLitRightIndicator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_blend_mode(ui_FullLitRightIndicator, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_FullLitRightIndicator, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UnlitLeftIndicator = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_UnlitLeftIndicator, &ui_img_indicator_right_unlit_png);
    lv_obj_set_width(ui_UnlitLeftIndicator, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_UnlitLeftIndicator, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_UnlitLeftIndicator, -75);
    lv_obj_set_y(ui_UnlitLeftIndicator, -10);
    lv_obj_set_align(ui_UnlitLeftIndicator, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_UnlitLeftIndicator, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_UnlitLeftIndicator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_UnlitLeftIndicator, 1800);

    ui_FirstPartLitLeftIndicator = lv_img_create(ui_UnlitLeftIndicator);
    lv_img_set_src(ui_FirstPartLitLeftIndicator, &ui_img_indicator_right_partial_png);
    lv_obj_set_width(ui_FirstPartLitLeftIndicator, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FirstPartLitLeftIndicator, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_FirstPartLitLeftIndicator, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_FirstPartLitLeftIndicator, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_FirstPartLitLeftIndicator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_FirstPartLitLeftIndicator, 1800);
    lv_obj_set_style_blend_mode(ui_FirstPartLitLeftIndicator, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_FirstPartLitLeftIndicator, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SecondPartLitLeftIndicator = lv_img_create(ui_UnlitLeftIndicator);
    lv_img_set_src(ui_SecondPartLitLeftIndicator, &ui_img_indicator_right_partial2_png);
    lv_obj_set_width(ui_SecondPartLitLeftIndicator, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SecondPartLitLeftIndicator, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SecondPartLitLeftIndicator, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SecondPartLitLeftIndicator, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SecondPartLitLeftIndicator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_SecondPartLitLeftIndicator, 1800);
    lv_obj_set_style_blend_mode(ui_SecondPartLitLeftIndicator, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_SecondPartLitLeftIndicator, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FullLitLeftIndicator = lv_img_create(ui_UnlitLeftIndicator);
    lv_img_set_src(ui_FullLitLeftIndicator, &ui_img_indicator_right_lit_png);
    lv_obj_set_width(ui_FullLitLeftIndicator, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FullLitLeftIndicator, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_FullLitLeftIndicator, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_FullLitLeftIndicator, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_FullLitLeftIndicator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_FullLitLeftIndicator, 1800);
    lv_obj_set_style_blend_mode(ui_FullLitLeftIndicator, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_FullLitLeftIndicator, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatBattOk = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_StatBattOk, &ui_img_status_batt_ok_png);
    lv_obj_set_width(ui_StatBattOk, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StatBattOk, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_StatBattOk, 300);
    lv_obj_set_y(ui_StatBattOk, -300);
    lv_obj_set_align(ui_StatBattOk, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_StatBattOk, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_StatBattOk, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_StatBattWarn = lv_img_create(ui_StatBattOk);
    lv_img_set_src(ui_StatBattWarn, &ui_img_status_batt_warn_png);
    lv_obj_set_width(ui_StatBattWarn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StatBattWarn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_StatBattWarn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_StatBattWarn, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_StatBattWarn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_blend_mode(ui_StatBattWarn, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_StatBattWarn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatTempOk = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_StatTempOk, &ui_img_status_temp_ok_png);
    lv_obj_set_width(ui_StatTempOk, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StatTempOk, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_StatTempOk, 300);
    lv_obj_set_y(ui_StatTempOk, -200);
    lv_obj_set_align(ui_StatTempOk, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_StatTempOk, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_StatTempOk, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_StatTempWarn = lv_img_create(ui_StatTempOk);
    lv_img_set_src(ui_StatTempWarn, &ui_img_status_temp_warn_png);
    lv_obj_set_width(ui_StatTempWarn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StatTempWarn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_StatTempWarn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_StatTempWarn, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_StatTempWarn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_blend_mode(ui_StatTempWarn, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_StatTempWarn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatCommsOk = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_StatCommsOk, &ui_img_status_comms_ok_png);
    lv_obj_set_width(ui_StatCommsOk, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StatCommsOk, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_StatCommsOk, 300);
    lv_obj_set_y(ui_StatCommsOk, -100);
    lv_obj_set_align(ui_StatCommsOk, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_StatCommsOk, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_StatCommsOk, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_StatCommsWarn = lv_img_create(ui_StatCommsOk);
    lv_img_set_src(ui_StatCommsWarn, &ui_img_status_comms_warn_png);
    lv_obj_set_width(ui_StatCommsWarn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StatCommsWarn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_StatCommsWarn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_StatCommsWarn, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_StatCommsWarn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_blend_mode(ui_StatCommsWarn, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_StatCommsWarn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatSolarOk = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_StatSolarOk, &ui_img_status_solar_ok_png);
    lv_obj_set_width(ui_StatSolarOk, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StatSolarOk, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_StatSolarOk, -300);
    lv_obj_set_y(ui_StatSolarOk, -100);
    lv_obj_set_align(ui_StatSolarOk, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_StatSolarOk, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_StatSolarOk, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_StatSolarWarn = lv_img_create(ui_StatSolarOk);
    lv_img_set_src(ui_StatSolarWarn, &ui_img_status_solar_warn_png);
    lv_obj_set_width(ui_StatSolarWarn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StatSolarWarn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_StatSolarWarn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_StatSolarWarn, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_StatSolarWarn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_blend_mode(ui_StatSolarWarn, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_StatSolarWarn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatCtrlOk = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_StatCtrlOk, &ui_img_status_ctrl_ok_png);
    lv_obj_set_width(ui_StatCtrlOk, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StatCtrlOk, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_StatCtrlOk, -300);
    lv_obj_set_y(ui_StatCtrlOk, -200);
    lv_obj_set_align(ui_StatCtrlOk, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_StatCtrlOk, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_StatCtrlOk, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_StatCtrlWarn = lv_img_create(ui_StatCtrlOk);
    lv_img_set_src(ui_StatCtrlWarn, &ui_img_status_ctrl_warn_png);
    lv_obj_set_width(ui_StatCtrlWarn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StatCtrlWarn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_StatCtrlWarn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_StatCtrlWarn, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_StatCtrlWarn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_blend_mode(ui_StatCtrlWarn, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_StatCtrlWarn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatMotorOk = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_StatMotorOk, &ui_img_status_motor_ok_png);
    lv_obj_set_width(ui_StatMotorOk, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StatMotorOk, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_StatMotorOk, -300);
    lv_obj_set_y(ui_StatMotorOk, -300);
    lv_obj_set_align(ui_StatMotorOk, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_StatMotorOk, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_StatMotorOk, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_StatMotorWarn = lv_img_create(ui_StatMotorOk);
    lv_img_set_src(ui_StatMotorWarn, &ui_img_status_motor_warn_png);
    lv_obj_set_width(ui_StatMotorWarn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StatMotorWarn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_StatMotorWarn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_StatMotorWarn, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_StatMotorWarn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_blend_mode(ui_StatMotorWarn, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_StatMotorWarn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WarningText = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_WarningText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WarningText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WarningText, 0);
    lv_obj_set_y(ui_WarningText, 200);
    lv_obj_set_align(ui_WarningText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WarningText, "Warning");
    lv_obj_set_style_text_color(ui_WarningText, lv_color_hex(0xFFB020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WarningText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WarningText, &ui_font_InterSemiBold22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_WarningText, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_WarningText, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_Screen1 = ui_Screen1;
    uic_Speedometer = ui_Speedometer;
    uic_Panel10 = ui_Panel10;
    uic_Panel11 = ui_Panel11;
    uic_Tick11 = ui_Tick11;
    uic_kph1 = ui_kph1;
    uic_Speed1 = ui_Speed1;
    uic_Tick12 = ui_Tick12;
    uic_Tick13 = ui_Tick13;
    uic_Tick14 = ui_Tick14;
    uic_Tick15 = ui_Tick15;
    uic_Tick16 = ui_Tick16;
    uic_Tick17 = ui_Tick17;
    uic_Tick18 = ui_Tick18;
    uic_Tick19 = ui_Tick19;
    uic_Tick20 = ui_Tick20;
    uic_Tick21 = ui_Tick21;
    uic_SpeedSlider1 = ui_SpeedSlider1;
    uic_SEMLogo = ui_SEMLogo;
    uic_BattTempLabel = ui_BattTempLabel;
    uic_BattPercLabel = ui_BattPercLabel;
    uic_BattPerc4 = ui_BattPerc4;
    uic_BattPercSlider3 = ui_BattPercSlider3;
    uic_BattPerc2 = ui_BattPerc2;
    uic_DrivingStateLabel = ui_DrivingStateLabel;
    uic_SteeringAngleLabel = ui_SteeringAngleLabel;
    uic_PowerOut = ui_PowerOut;
    uic_PowerIn = ui_PowerIn;
    uic_PWROUT = ui_PWROUT;
    uic_PWRIN = ui_PWRIN;
    uic_UnlitWarningLight = ui_UnlitWarningLight;
    uic_LitWarningLight = ui_LitWarningLight;
    uic_UnlitFullBeam = ui_UnlitFullBeam;
    uic_LitFullBeam = ui_LitFullBeam;
    uic_UnlitRightIndicator = ui_UnlitRightIndicator;
    uic_FirstPartLitRightIndicator = ui_FirstPartLitRightIndicator;
    uic_SecondPartLitRightIndicator = ui_SecondPartLitRightIndicator;
    uic_FullLitRightIndicator = ui_FullLitRightIndicator;
    uic_UnlitLeftIndicator = ui_UnlitLeftIndicator;
    uic_FirstPartLitLeftIndicator = ui_FirstPartLitLeftIndicator;
    uic_SecondPartLitLeftIndicator = ui_SecondPartLitLeftIndicator;
    uic_FullLitLeftIndicator = ui_FullLitLeftIndicator;
    uic_StatBattOk = ui_StatBattOk;
    uic_StatBattWarn = ui_StatBattWarn;
    uic_StatTempOk = ui_StatTempOk;
    uic_StatTempWarn = ui_StatTempWarn;
    uic_StatCommsOk = ui_StatCommsOk;
    uic_StatCommsWarn = ui_StatCommsWarn;
    uic_StatSolarWarn = ui_StatSolarWarn;
    uic_StatCtrlOk = ui_StatCtrlOk;
    uic_StatCtrlWarn = ui_StatCtrlWarn;
    uic_StatMotorOk = ui_StatMotorOk;
    uic_StatMotorWarn = ui_StatMotorWarn;
    uic_WarningText = ui_WarningText;

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    uic_Screen1 = NULL;
    ui_Screen1 = NULL;
    uic_Speedometer = NULL;
    ui_Speedometer = NULL;
    uic_Panel10 = NULL;
    ui_Panel10 = NULL;
    uic_Panel11 = NULL;
    ui_Panel11 = NULL;
    uic_Tick11 = NULL;
    ui_Tick11 = NULL;
    uic_kph1 = NULL;
    ui_kph1 = NULL;
    uic_Speed1 = NULL;
    ui_Speed1 = NULL;
    uic_Tick12 = NULL;
    ui_Tick12 = NULL;
    uic_Tick13 = NULL;
    ui_Tick13 = NULL;
    uic_Tick14 = NULL;
    ui_Tick14 = NULL;
    uic_Tick15 = NULL;
    ui_Tick15 = NULL;
    uic_Tick16 = NULL;
    ui_Tick16 = NULL;
    uic_Tick17 = NULL;
    ui_Tick17 = NULL;
    uic_Tick18 = NULL;
    ui_Tick18 = NULL;
    uic_Tick19 = NULL;
    ui_Tick19 = NULL;
    uic_Tick20 = NULL;
    ui_Tick20 = NULL;
    uic_Tick21 = NULL;
    ui_Tick21 = NULL;
    uic_SpeedSlider1 = NULL;
    ui_SpeedSlider1 = NULL;
    uic_SEMLogo = NULL;
    ui_SEMLogo = NULL;
    uic_BattTempLabel = NULL;
    ui_BattTempLabel = NULL;
    uic_BattPercLabel = NULL;
    ui_BattPercLabel = NULL;
    uic_BattPerc4 = NULL;
    ui_BattPerc4 = NULL;
    uic_BattPercSlider3 = NULL;
    ui_BattPercSlider3 = NULL;
    uic_BattPerc2 = NULL;
    ui_BattPerc2 = NULL;
    uic_DrivingStateLabel = NULL;
    ui_DrivingStateLabel = NULL;
    uic_SteeringAngleLabel = NULL;
    ui_SteeringAngleLabel = NULL;
    uic_PowerOut = NULL;
    ui_PowerOut = NULL;
    uic_PowerIn = NULL;
    ui_PowerIn = NULL;
    uic_PWROUT = NULL;
    ui_PWROUT = NULL;
    uic_PWRIN = NULL;
    ui_PWRIN = NULL;
    uic_UnlitWarningLight = NULL;
    ui_UnlitWarningLight = NULL;
    uic_LitWarningLight = NULL;
    ui_LitWarningLight = NULL;
    uic_UnlitFullBeam = NULL;
    ui_UnlitFullBeam = NULL;
    uic_LitFullBeam = NULL;
    ui_LitFullBeam = NULL;
    uic_UnlitRightIndicator = NULL;
    ui_UnlitRightIndicator = NULL;
    uic_FirstPartLitRightIndicator = NULL;
    ui_FirstPartLitRightIndicator = NULL;
    uic_SecondPartLitRightIndicator = NULL;
    ui_SecondPartLitRightIndicator = NULL;
    uic_FullLitRightIndicator = NULL;
    ui_FullLitRightIndicator = NULL;
    uic_UnlitLeftIndicator = NULL;
    ui_UnlitLeftIndicator = NULL;
    uic_FirstPartLitLeftIndicator = NULL;
    ui_FirstPartLitLeftIndicator = NULL;
    uic_SecondPartLitLeftIndicator = NULL;
    ui_SecondPartLitLeftIndicator = NULL;
    uic_FullLitLeftIndicator = NULL;
    ui_FullLitLeftIndicator = NULL;
    uic_StatBattOk = NULL;
    ui_StatBattOk = NULL;
    uic_StatBattWarn = NULL;
    ui_StatBattWarn = NULL;
    uic_StatTempOk = NULL;
    ui_StatTempOk = NULL;
    uic_StatTempWarn = NULL;
    ui_StatTempWarn = NULL;
    uic_StatCommsOk = NULL;
    ui_StatCommsOk = NULL;
    uic_StatCommsWarn = NULL;
    ui_StatCommsWarn = NULL;
    ui_StatSolarOk = NULL;
    uic_StatSolarWarn = NULL;
    ui_StatSolarWarn = NULL;
    uic_StatCtrlOk = NULL;
    ui_StatCtrlOk = NULL;
    uic_StatCtrlWarn = NULL;
    ui_StatCtrlWarn = NULL;
    uic_StatMotorOk = NULL;
    ui_StatMotorOk = NULL;
    uic_StatMotorWarn = NULL;
    ui_StatMotorWarn = NULL;
    uic_WarningText = NULL;
    ui_WarningText = NULL;

}
