// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: ScreenUI

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Speedometer;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_Tick11;
extern lv_obj_t * ui_kph1;
extern lv_obj_t * ui_Speed1;
extern lv_obj_t * ui_Tick12;
extern lv_obj_t * ui_Tick13;
extern lv_obj_t * ui_Tick14;
extern lv_obj_t * ui_Tick15;
extern lv_obj_t * ui_Tick16;
extern lv_obj_t * ui_Tick17;
extern lv_obj_t * ui_Tick18;
extern lv_obj_t * ui_Tick19;
extern lv_obj_t * ui_Tick20;
extern lv_obj_t * ui_Tick21;
extern lv_obj_t * ui_SpeedSlider1;
extern lv_obj_t * ui_SEMLogo;
extern lv_obj_t * ui_BattTempLabel;
extern lv_obj_t * ui_BattPercLabel;
extern lv_obj_t * ui_BattPerc4;
extern lv_obj_t * ui_BattPercSlider3;
extern lv_obj_t * ui_BattPerc2;
extern lv_obj_t * ui_DrivingStateLabel;
extern lv_obj_t * ui_SteeringAngleLabel;
extern lv_obj_t * ui_PowerOut;
extern lv_obj_t * ui_PowerIn;
extern lv_obj_t * ui_PWROUT;
extern lv_obj_t * ui_PWRIN;
extern lv_obj_t * ui_UnlitWarningLight;
extern lv_obj_t * ui_LitWarningLight;
extern lv_obj_t * ui_UnlitFullBeam;
extern lv_obj_t * ui_LitFullBeam;
extern lv_obj_t * ui_UnlitRightIndicator;
extern lv_obj_t * ui_FirstPartLitRightIndicator;
extern lv_obj_t * ui_SecondPartLitRightIndicator;
extern lv_obj_t * ui_FullLitRightIndicator;
extern lv_obj_t * ui_UnlitLeftIndicator;
extern lv_obj_t * ui_FirstPartLitLeftIndicator;
extern lv_obj_t * ui_SecondPartLitLeftIndicator;
extern lv_obj_t * ui_FullLitLeftIndicator;
extern lv_obj_t * ui_StatBattOk;
extern lv_obj_t * ui_StatBattWarn;
extern lv_obj_t * ui_StatTempOk;
extern lv_obj_t * ui_StatTempWarn;
extern lv_obj_t * ui_StatCommsOk;
extern lv_obj_t * ui_StatCommsWarn;
extern lv_obj_t * ui_StatSolarOk;
extern lv_obj_t * ui_StatSolarWarn;
extern lv_obj_t * ui_StatCtrlOk;
extern lv_obj_t * ui_StatCtrlWarn;
extern lv_obj_t * ui_StatMotorOk;
extern lv_obj_t * ui_StatMotorWarn;
extern lv_obj_t * ui_WarningText;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Screen1;
extern lv_obj_t * uic_Speedometer;
extern lv_obj_t * uic_Panel10;
extern lv_obj_t * uic_Panel11;
extern lv_obj_t * uic_Tick11;
extern lv_obj_t * uic_kph1;
extern lv_obj_t * uic_Speed1;
extern lv_obj_t * uic_Tick12;
extern lv_obj_t * uic_Tick13;
extern lv_obj_t * uic_Tick14;
extern lv_obj_t * uic_Tick15;
extern lv_obj_t * uic_Tick16;
extern lv_obj_t * uic_Tick17;
extern lv_obj_t * uic_Tick18;
extern lv_obj_t * uic_Tick19;
extern lv_obj_t * uic_Tick20;
extern lv_obj_t * uic_Tick21;
extern lv_obj_t * uic_SpeedSlider1;
extern lv_obj_t * uic_SEMLogo;
extern lv_obj_t * uic_BattTempLabel;
extern lv_obj_t * uic_BattPercLabel;
extern lv_obj_t * uic_BattPerc4;
extern lv_obj_t * uic_BattPercSlider3;
extern lv_obj_t * uic_BattPerc2;
extern lv_obj_t * uic_DrivingStateLabel;
extern lv_obj_t * uic_SteeringAngleLabel;
extern lv_obj_t * uic_PowerOut;
extern lv_obj_t * uic_PowerIn;
extern lv_obj_t * uic_PWROUT;
extern lv_obj_t * uic_PWRIN;
extern lv_obj_t * uic_UnlitWarningLight;
extern lv_obj_t * uic_LitWarningLight;
extern lv_obj_t * uic_UnlitFullBeam;
extern lv_obj_t * uic_LitFullBeam;
extern lv_obj_t * uic_UnlitRightIndicator;
extern lv_obj_t * uic_FirstPartLitRightIndicator;
extern lv_obj_t * uic_SecondPartLitRightIndicator;
extern lv_obj_t * uic_FullLitRightIndicator;
extern lv_obj_t * uic_UnlitLeftIndicator;
extern lv_obj_t * uic_FirstPartLitLeftIndicator;
extern lv_obj_t * uic_SecondPartLitLeftIndicator;
extern lv_obj_t * uic_FullLitLeftIndicator;
extern lv_obj_t * uic_StatBattOk;
extern lv_obj_t * uic_StatBattWarn;
extern lv_obj_t * uic_StatTempOk;
extern lv_obj_t * uic_StatTempWarn;
extern lv_obj_t * uic_StatCommsOk;
extern lv_obj_t * uic_StatCommsWarn;
extern lv_obj_t * uic_StatSolarWarn;
extern lv_obj_t * uic_StatCtrlOk;
extern lv_obj_t * uic_StatCtrlWarn;
extern lv_obj_t * uic_StatMotorOk;
extern lv_obj_t * uic_StatMotorWarn;
extern lv_obj_t * uic_WarningText;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

