// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: ScreenUI

#ifndef _UI_THEMES_H
#define _UI_THEMES_H

#ifdef __cplusplus
extern "C" {
#endif

#define UI_THEME_COLOR_BACKGROUND 0
#define UI_THEME_COLOR_TEXTCOLOUR 1
#define UI_THEME_COLOR_GREENBAR 2
#define UI_THEME_COLOR_YELLOWBAR 3
#define UI_THEME_COLOR_REDBAR 4

#define UI_THEME_DEFAULT 0

extern const ui_theme_variable_t _ui_theme_color_Background[1];
extern const ui_theme_variable_t _ui_theme_alpha_Background[1];

extern const ui_theme_variable_t _ui_theme_color_TextColour[1];
extern const ui_theme_variable_t _ui_theme_alpha_TextColour[1];

extern const ui_theme_variable_t _ui_theme_color_GreenBar[1];
extern const ui_theme_variable_t _ui_theme_alpha_GreenBar[1];

extern const ui_theme_variable_t _ui_theme_color_YellowBar[1];
extern const ui_theme_variable_t _ui_theme_alpha_YellowBar[1];

extern const ui_theme_variable_t _ui_theme_color_RedBar[1];
extern const ui_theme_variable_t _ui_theme_alpha_RedBar[1];

extern const uint32_t * ui_theme_colors[1];
extern const uint8_t * ui_theme_alphas[1];
extern uint8_t ui_theme_idx;

void ui_theme_set(uint8_t theme_idx);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
