// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: ScreenUI

#include "ui.h"


const ui_theme_variable_t _ui_theme_color_Background[1] = {0x141034};
const ui_theme_variable_t _ui_theme_alpha_Background[1] = {255};

const ui_theme_variable_t _ui_theme_color_TextColour[1] = {0xFFFFFF};
const ui_theme_variable_t _ui_theme_alpha_TextColour[1] = {255};

const ui_theme_variable_t _ui_theme_color_GreenBar[1] = {0x007900};
const ui_theme_variable_t _ui_theme_alpha_GreenBar[1] = {255};

const ui_theme_variable_t _ui_theme_color_YellowBar[1] = {0xC8C800};
const ui_theme_variable_t _ui_theme_alpha_YellowBar[1] = {255};

const ui_theme_variable_t _ui_theme_color_RedBar[1] = {0xAC0000};
const ui_theme_variable_t _ui_theme_alpha_RedBar[1] = {255};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;


void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

